package com.example.friendly_travel.model

import com.example.friendly_travel.R

object WisataData {
    val wisata = listOf(
        Wisata(
            id=0,
            name = "Pura Tanah Lot",
            category = "Budaya",
            alamat = " ",
            photo = R.drawable.tanahlot,
            deskripsi =  "Pura Tanah Lot adalah sbuah ikon dari wisata Bali yang wajib dikunjungi ketika Anda pelesir ke sana. Pura ini terdiri dari dua bangunan yang terpisah oleh lautan. Bangunan pertama terletak di bongkahan batu besar dan bangunan yang kedua berada di tebing. Pengunjung yang datang ke sini bisa menyeberang ke pura di tengah laut saat air sedang surut." ,
            rating =  8.6,
            harga = 30.0000,

        ),
        Wisata(
            id=1,
            name = "Pantai Kuta",
            category = "Pantai",
            alamat = " ",
            photo = R.drawable.pantaikuta,
            deskripsi =  "Pantai Kuta Bali merupakan salah satu tujuan wisata terkenal di Bali karena segudang keistimewaan dan daya tariknya. Salah satu alasan mengapa tempat wisata ini banyak dikunjungi wisatawan adalah akses dan transportasinya yang mudah dengan lokasi yang strategis. Simak artikel satu ini untuk mengetahui lokasi, harga tiket masuk, dan berbagai daya tarik yang dimilikinya!" ,
            rating =  8.6,
            harga = 10.0000,
        ),
        Wisata(
            id=2,
            name = "Pura Besakih",
            category = "Budaya",
            alamat = " ",
            photo = R.drawable.urabesaikh,
            deskripsi =  "Pura Besakih adalah salah satu pura untuk tempat peribadatan umat Hindu di Bali. Pura ini dikenal paling besar dan sakral. Banyak upacara keagamaan besar diadakan di sini setiap tahunnya.",
            rating =  8.6,
            harga = 30.0000,
        ),
        Wisata(
            id=3,
            name = "Pantai Tanjung Benoa",
            category = "Pantai",
            alamat = "Nusa Dua Bali ",
            photo = R.drawable.benoa,
            deskripsi =  "Tanjung Benoa adalah sebuah peninsula yang lokasinya berada di sebelah utara tempat wisata Nusa Dua Bali. Walaupun kawasan objek wisata Tanjung Benoa Bali tidak semewah jika di bandingkan dengan kawasan Nusa Dua, namun Tanjung Benoa sebagai tempat wisata di pulau Bali memiliki keunikan khusus.",
            rating =  8.85,
            harga = 10.0000,
        ),
        Wisata(
            id=4,
            name = "Pura Tirta Empul",
            category = "Budaya",
            alamat = " ",
            photo = R.drawable.empul4,
            deskripsi =  "Pura Tirta Empul adalah nama sebuah pura yang terletak di desa Manukaya, kecamatan Tampak Siring, kabupaten Gianyar. Keunikan arsitektur dan adanya mata air pada area dalam pura, membuat pura Tirta Empul menarik banyak kunjungan wisatawan, baik wisatawan mancanegara maupun wisatawan domestik. Jarak Tirta Empul dari airport Ngurah Rai, kurang lebih 52 kilometer yang memerlukan waktu 1 jam 30 menit.",
            rating =  8.8,
            harga = 15.0000,
        ),
        Wisata(
            id=5,
            name = "Pantai Pandawa",
            category = "Pantai",
            alamat = " ",
            photo = R.drawable.antaiandawa,
            deskripsi =  "Pantai Pandawa di Kabupaten Badung, Bali, merupakan destinasi wisata terkenal yang menawarkan pemandangan tebing-tebing yang menakjubkan, pasir putih, dan air kehijauan yang indah.",
            rating =  8.2,
            harga = 8.0000,
        ),
        Wisata(
            id=6,
            name = "Goa",
            category = "Goa",
            alamat = " ",
            photo = R.drawable.menu3,
            deskripsi =  "Salah satu yang unik dari pura yang terletak di Jalan Tirta, Manukaya, Tampaksiring, Gianyar, Bali ini adalah adanya kolam untuk mandi. Di salah satu sudut pura ada kolam pemandian yang di bagian atasnya terdapat beberapa pancuran air. Anda bisa ikut mandi di sini untuk menyucikan diri dan menikmati keindahan pura.",
            rating =  9.0,
            harga = 15.0000,
        ),
        Wisata(
            id=7,
            name = "Goa",
            category = "Goa",
            alamat = " ",
            photo = R.drawable.menu3,
            deskripsi =  "Pura Besakih dikenal paling besar dan sakral bagi penganut Hindu di Bali. Sebagai pura yang besar, di sekitarnya ada 18 pura pendamping. Lokasinya berada di Besakih, Karangasem. Kalau kamu ke sini, kamu dapat melihat keindahan budaya Bali yang terwujud dari desain dan ornamen pura.",
            rating =  8.6,
            harga = 10.0000,
        ),
        Wisata(
            id=8,
            name = "Goa",
            category = "Goa",
            alamat = " ",
            photo = R.drawable.menu3,
            deskripsi =  "Pura Besakih dikenal paling besar dan sakral bagi penganut Hindu di Bali. Sebagai pura yang besar, di sekitarnya ada 18 pura pendamping. Lokasinya berada di Besakih, Karangasem. Kalau kamu ke sini, kamu dapat melihat keindahan budaya Bali yang terwujud dari desain dan ornamen pura.",
            rating =  8.6,
            harga = 10.0000,
        ),
        Wisata(
            id=9,
            name = "Gunung",
            category = "Gunung",
            alamat = " ",
            photo = R.drawable.menu3,
            deskripsi =  "Pura Besakih dikenal paling besar dan sakral bagi penganut Hindu di Bali. Sebagai pura yang besar, di sekitarnya ada 18 pura pendamping. Lokasinya berada di Besakih, Karangasem. Kalau kamu ke sini, kamu dapat melihat keindahan budaya Bali yang terwujud dari desain dan ornamen pura.",
            rating =  8.6,
            harga = 10.0000,
        ),
        Wisata(
            id=10,
            name = "Gunung",
            category = "Gunung",
            alamat = " ",
            photo = R.drawable.menu3,
            deskripsi =  "Pura Besakih dikenal paling besar dan sakral bagi penganut Hindu di Bali. Sebagai pura yang besar, di sekitarnya ada 18 pura pendamping. Lokasinya berada di Besakih, Karangasem. Kalau kamu ke sini, kamu dapat melihat keindahan budaya Bali yang terwujud dari desain dan ornamen pura.",
            rating =  8.6,
            harga = 10.0000,
        ),
        Wisata(
            id=11,
            name = "Gunung",
            category = "Gunung",
            alamat = " ",
            photo = R.drawable.menu3,
            deskripsi =  "Pura Besakih dikenal paling besar dan sakral bagi penganut Hindu di Bali. Sebagai pura yang besar, di sekitarnya ada 18 pura pendamping. Lokasinya berada di Besakih, Karangasem. Kalau kamu ke sini, kamu dapat melihat keindahan budaya Bali yang terwujud dari desain dan ornamen pura.",
            rating =  8.6,
            harga = 10.0000,
        ),

    )
}